tecnicas/apps/mactor/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import listar_estudios, crearEstudio, editar_estudio, consultar_estudio,\
    crear_actor, listar_actores, editar_actor, consultar_actor, eliminar_actor, \
    crear_ficha, lista_fichas, editar_ficha, consultar_ficha, eliminar_ficha, consultar_ficha_mid, \
    crear_objetivo, listar_objetivos, editar_objetivo, consultar_objetivo, eliminar_objetivo, \
    crear_relacion_mid, generar_matriz_mid, generar_matriz_midi, generar_matriz_maxima, generar_matriz_ri, \
    generar_matriz_balance, generar_indicador_estabilidad, crear_1mao, crear_2mao, generar_matriz_mao,\
    generar_matrices_caa_daa, consultar_actores_faltantes, consultar_objetivos_faltantes, \
    crear_informe, exportar_estudio_xls, \
    histograma_mid, datos_histograma_mid, histograma_ri, datos_histograma_ri, \
    histograma_implicacion, histograma_movilizacion, datos_histogramas_mao,  \
    datos_histograma_caa_daa, histograma_caa_daa, \
    generar_mapa_midi, datos_mapa_midi, generar_mapa_caa_daa, datos_mapa_caa_daa, \
    generar_grafo_caa, datos_grafo_caa, generar_grafo_daa, datos_grafo_daa, \
    activar_consenso_influencias, activar_consenso_mao, activar_consenso_caa_daa

# nombre de la url, view que respondera y el parametro name
urlpatterns = [

    # Urls modelo Estudio_mactor
    url(r'^agregar_estudio/$', crearEstudio.as_view(), name='estudio'),
    url(r'^lista_estudios', login_required(listar_estudios), name='lista_estudios'),
    url(r'^editar_estudio/(?P<idEstudio>\d+)/$', login_required(editar_estudio), name='editar_estudio'),
    url(r'^consultar_estudio/$', login_required(consultar_estudio)),

    # Urls modelo Actor
    url(r'agregar_actor/$', login_required(crear_actor)),
    url(r'eliminar_actor/$', login_required(eliminar_actor)),
    url(r'editar_actor/$', login_required(editar_actor)),
    url(r'^lista_actores/(?P<idEstudio>\d+)/$', login_required(listar_actores), name='lista_actores'),
    url(r'consultar_actor', login_required(consultar_actor)),

    # Urls modelo Ficha
    url(r'^agregar_ficha/(?P<idEstudio>\d+)/$', login_required(crear_ficha), name='ficha'),
    url(r'eliminar_ficha/$', login_required(eliminar_ficha)),
    url(r'consultar_ficha/$', login_required(consultar_ficha)),
    url(r'^editar_ficha/(?P<idFicha>\d+)/$', login_required(editar_ficha), name='editar_ficha'),
    url(r'lista_fichas/(?P<idEstudio>\d+)/$', login_required(lista_fichas), name='lista_fichas'),
    url(r'consultar_ficha_mid/$', login_required(consultar_ficha_mid)),

    # Urls modelo Objetivo
    url(r'agregar_objetivo/$', login_required(crear_objetivo)),
    url(r'^lista_objetivos/(?P<idEstudio>\d+)/$', login_required(listar_objetivos), name='lista_objetivos'),
    url(r'eliminar_objetivo/$', login_required(eliminar_objetivo)),
    url(r'editar_objetivo/$', login_required(editar_objetivo)),
    url(r'consultar_objetivo', login_required(consultar_objetivo)),

    # Urls modelo Relacion_MID y matrices
    url(r'^agregar_influencia/(?P<idEstudio>\d+)/$', login_required(crear_relacion_mid), name='influencia'),
    url(r'^matriz_mid/(?P<idEstudio>\d+)/$', login_required(generar_matriz_mid), name='matriz_mid'),
    url(r'^matriz_midi/(?P<idEstudio>\d+)/$', login_required(generar_matriz_midi), name='matriz_midi'),
    url(r'^matriz_maxima/(?P<idEstudio>\d+)/$', login_required(generar_matriz_maxima), name='matriz_maxima'),
    url(r'^matriz_ri/(?P<idEstudio>\d+)/$', login_required(generar_matriz_ri), name='matriz_ri'),
    url(r'^matriz_balance/(?P<idEstudio>\d+)/$', login_required(generar_matriz_balance), name='matriz_balance'),
    url(r'^estabilidad/(?P<idEstudio>\d+)/$', login_required(generar_indicador_estabilidad), name='estabilidad'),

    # Urls modelo Relacion_MAO y matrices
    url(r'^1mao/(?P<idEstudio>\d+)/$', login_required(crear_1mao), name='1mao'),
    url(r'^2mao/(?P<idEstudio>\d+)/$', login_required(crear_2mao), name='2mao'),
    url(r'^matriz_mao/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matriz_mao), name='matriz_mao'),
    url(r'^matriz_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matrices_caa_daa), name='caa_daa'),

    # Urls consultas ajax
    url(r'mid-ajax/$', login_required(consultar_actores_faltantes)),  # obtiene lista actores X registrados en la mid
    url(r'mao-ajax/$', login_required(consultar_objetivos_faltantes)),  # obtiene lista objetivos X registrados en la mao

    # Urls histogramas de influencia
    url(r'^histograma_mid/(?P<idEstudio>\d+)/$', login_required(histograma_mid), name='histograma_mid'),
    url(r'datos_histograma_mid', login_required(datos_histograma_mid)),
    url(r'^histograma_ri/(?P<idEstudio>\d+)/$', login_required(histograma_ri), name='histograma_ri'),
    url(r'datos_histograma_ri', login_required(datos_histograma_ri)),

    # Urls histogramas mao
    url(r'^histograma_implicacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_implicacion),
        name='implicacion'),
    url(r'^histograma_movilizacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_movilizacion),
        name='movilizacion'),
    url(r'datos_histograma', login_required(datos_histogramas_mao)),

    # Urls mapa actores
    url(r'^mapa_actores/(?P<idEstudio>\d+)/$', login_required(generar_mapa_midi), name='mapa_actores'),
    url(r'datos_plano_midi', login_required(datos_mapa_midi)),

    # Urls graficos caa y daa
    url(r'^mapa_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_mapa_caa_daa), name='mapa_caa_daa'),
    url(r'datos_mapa_caa_daa', login_required(datos_mapa_caa_daa)),
    url(r'^histograma_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', histograma_caa_daa, name='hist_caa_daa'),
    url(r'datos_caa_daa', login_required(datos_histograma_caa_daa)),
    url(r'^grafo_caa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_caa), name='grafo_caa'),
    url(r'datos_grafo_caa', login_required(datos_grafo_caa)),
    url(r'^grafo_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_daa), name='grafo_daa'),
    url(r'datos_grafo_daa', login_required(datos_grafo_daa)),

    # Urls exportar a excel
    url(r'exportar_estudios/xls/(?P<idEstudio>\d+)/$', login_required(exportar_estudio_xls), name='estudios_xls'),

    # Urls consensos
    url(r'^consenso_influencias/(?P<idEstudio>\d+)/(?P<tipo>\d)/', login_required(activar_consenso_influencias), name='consenso_influencias'),
    url(r'^consenso_mao/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_mao), name='consenso_mao'),
    url(r'^consenso_caa_daa/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)/', login_required(activar_consenso_caa_daa), name='consenso_caa_daa'),

    # Urls modelo informe final
    url(r'^informe_final/(?P<idEstudio>\d+)/$', login_required(crear_informe), name='informe_final'),

]

tecnicas/tecnicas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    # urls vista administracion
    url(r'^admin/', admin.site.urls, ),
    # urls de la app mactor
    url(r'^mactor/', include('apps.mactor.urls', namespace="mactor")),
    # urls de la app entrevista
    url(r'^entrevista/', include('apps.entrevista.urls', namespace="entrevista")),
    # urls vista control de usuarios paquete Registration
    url(r'^accounts/', include('registration.backends.default.urls'))
]

tecnicas/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>{% block favicon_title %}Softprosp{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <!-- Style (css)-->
    {% include "css.html" %}

<!--bloque para archivos css extras-->
{% block extracss %}
{% endblock %}

    <meta name="robots" content="NONE,NOARCHIVE"/>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon/favicon.png'%}">
</head>

<body class="">
    <!-- Navbar-->
    {% include "navbar.html" %}
    <!-- Content-->
    <div class="content">
        <!-- Sidebar-->
        {% include "sidebar.html" %}
        <!-- Mainbar-->
        <!-- Main bar -->
        <div class="mainbar">
        <!-- Page heading -->
        <div class="page-head">
            <!-- Page heading -->
            <h2 class="pull-left">{% block head_title %} {% endblock %}
                <!-- page meta -->
                <span class="page-meta"></span>
            </h2>
            <!-- Breadcrumb -->
            <div class="bread-crumb pull-right"></div>
            <div class="clearfix"></div>
        </div>
        <!-- Matter -->
        <div class="matter">  <!--contenido importante-->
            <div class="container"> <!-- div de bootstrap para responsive-->
                <div class="row centered">
                    <div class="row"></div>
                    <div class="col-md-12">
                        {% block content %}
                        {% endblock %}
                    </div>
                    <footer id="footer"></footer>
                </div>
            </div>
            <!-- Matter ends -->
        </div>
        <!-- Mainbar ends -->
        <div class="clearfix"></div>
    </div>

    </div>

<!-- Scroll to top -->
<span class="totop"><a href="#"><i class="fa fa-chevron-up"></i></a></span>

<!-- JavaScript-->
{% include "js.html" %}

<!--bloque para archivos js extras-->
{% block extrajs %}
{% endblock %}

</body>
</html>

tecnicas/templates/css.html
{% load staticfiles %}

<!-- css propio -->
<link rel="stylesheet" href="{% static 'style/main.css'%}">
<!-- Bootstrap -->
<link rel="stylesheet" href="{% static 'style/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}">
<!-- Font awesome icon -->
<link rel="stylesheet" href="{% static 'style/font-awesome.css'%}">
<!-- jQuery UI -->
<link rel="stylesheet" href="{%static 'style/jquery-ui.css'%}">
<!-- Calendar -->
<link rel="stylesheet" href="{%static 'style/fullcalendar.css'%}">
<!-- prettyPhoto -->
<link rel="stylesheet" href="{%static 'style/prettyPhoto.css'%}">
<!-- Star rating -->
<link rel="stylesheet" href="{%static 'style/rateit.css'%}">
<!-- Date picker -->
<link rel="stylesheet" href="{% static 'style/bootstrap-datetimepicker.min.css'%}">
<!-- jQuery Gritter -->
<link rel="stylesheet" href="{% static 'style/jquery.gritter.css'%}">
<!-- CLEditor -->
<link rel="stylesheet" href="{% static 'style/jquery.cleditor.css'%}">
<!-- Bootstrap toggle -->
<link rel="stylesheet" href="{% static 'style/bootstrap-toggle-buttons.css'%}">
<!-- Main stylesheet -->
<link rel="stylesheet" href="{% static 'style/style.css'%}">
<!-- Widgets stylesheet -->
<link rel="stylesheet" href="{% static 'style/widgets.css'%}">
<!-- Responsive style from Bootstrap) -->
<link rel="stylesheet" href="{% static 'style/datepicker3.css'%}">
<!-- Bootstrap Switch-->
<link rel="stylesheet" href="{% static 'style/bootstrap-switch.css'%}">
<!--base.css-->
<link rel="stylesheet" href="{% static 'style/base.css'%}">
<!-- select2 -->
<link rel="stylesheet" href="{% static 'style/select2.css'%}"/>
<link rel="stylesheet" href="{% static 'style/select2-bootstrap.css'%}"/>
<link rel="stylesheet" href="{% static 'libs/sweetalert/sweet-alert.css'%}"/>
<link rel="stylesheet" href="{% static 'style/morris.css' %}"/>
<!--FontAwesome-->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>



<!---------------->

tecnicas/templates/js.html
{% load staticfiles %}

<!-- Javascript files -->
<!--
<script src="{% static 'jquery/jquery.min.js' %}"></script>-->
<!-- jQuery -->
<script src=" {% static 'js/jquery.js' %}"></script>
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- jQuery UI -->
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<!-- jQuery Gritter -->
<script src="{% static 'js/jquery.gritter.min.js' %}"></script>
<!-- Respond JS for IE8 -->
<script src="{% static 'js/respond.min.js' %}"></script>
<!-- HTML5 Support for IE -->
<script src="{% static 'js/html5shiv.js' %}"></script>
<!-- Custom JS -->
<script src="{% static 'js/custom.js' %}"></script>
<!-- Modal -------------------------------------->
<script src="{% static 'js/jquery.form.min.js' %}"></script>
<!-->
<script src="{% static 'js/filter.js' %}"></script>


<!--fontawesome-->

tecnicas/templates/navbar.html
 <div class="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
     <div class="container">
         <div class="navbar-header">
             <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="fa fa-bars"></span>
             </button>
             <a href="" class="navbar-brand">
                 <img src="/static/img/softprosp.png" id="branding"/>
             </a>
         </div>

         {% if request.user.is_authenticated %}
         <div class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
             <!-- Links -->
             <ul class="nav navbar-nav navbar-right">
                 <li class="dropdown">
                     <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                         <img src="/static/default/no-img.jpg" style="width:20px" alt="">
                         {{request.user}}
                         <b class="caret"></b>
                     </a>
                     <!-- Dropdown menu -->
                     <ul class="dropdown-menu">
                         <li><a href="#"><i class="fa fa-user"></i>Perfil</a></li>
                         <li><a href="{% url 'auth_password_change'%}"><i class="fa fa-lock"></i>Cambiar contraseña</a></li>
                         <li><a href="{% url 'auth_logout'%}"><i class="fa fa-sign-out"></i>Salir</a></li>
                     </ul>
                 </li>
             </ul>
             <!-- Notifications -->
             <ul class="nav navbar-nav navbar-right">
                 <!-- Comment button with number of latest comments count -->
                 <li class="dropdown dropdown-big">
                     <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                         <i class="fa fa-comments-o" aria-hidden="true"></i>Notificaciones <span id="notifications-badge" class="badge badge-info">0</span>
                     </a>
                     <ul class="dropdown-menu scrollable">
                         <li id="nots-list">
                             <!-- Heading - h5 -->
                             <h5><i class="fa fa-comments"></i> Notificaciones</h5>
                             <!-- Use hr tag to add border -->
                             <hr/>
                         </li>
                         <li>
                             <div class="drop-foot">
                                 <a href="">Ver todos.</a>
                             </div>
                         </li>
                     </ul>
                 </li>

                 <!-- Message button with number of latest messages count-->
                 <li class="dropdown dropdown-big">
                     <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                         <i class="fa fa-envelope-o"></i> Mensajes <span id="messages-badge" class="badge badge-info">0</span>
                     </a>
                     <ul class="dropdown-menu">
                         <li id="mess-list">
                             <!-- Heading - h5 -->
                             <h5><i class="fa fa-envelope-o"></i> Mensajes</h5>
                             <!-- Use hr tag to add border -->
                             <hr/>
                         </li>
                         <li>
                             <div class="drop-foot">
                                 <a href="">Ver todos.</a>
                             </div>
                         </li>
                     </ul>
                 </li>
             </ul>
         </div>
         {% endif %}
     </div>
 </div>

tecnicas/templates/sidebar.html
<!-- Sidebar -->
<div class="sidebar">
    <div class="sidebar-dropdown"><a href="#">Navigation</a></div>

    {% if request.user.is_authenticated %}
    <div class="sidebar-inner">
        <div class="sidebar-widget hidden-sm hidden-xs hidden-md" id="user_picture">
            <img src="/static/default/no-img.jpg" style="width:120px" alt="">
        </div>
        <div class="sidebar-widget">
            <p id="full_user_name">{{request.user}}</p>
        </div>
        <ul class="navi">
            <!-- Use the class nred, ngreen, nblue, nlightblue, nviolet or norange to add background color. You need to use this in <li> tag. -->
            <li class="nblue">
                <a href="{% url 'mactor:lista_estudios'%}">
                    <i class="fa fa-list"></i> Estudios MACTOR
                </a>
            </li>
            <li class="nblue">
                <a href="{% url 'entrevista:lista_estudios'%}">
                    <i class="fa fa-list"></i> Estudios Entrevista
                </a>
            </li>
            {%if request.user.is_superuser %}
            <li class="norange">
                <a href="http://localhost:8000/admin/">
                    <i class="fa fa-database"></i> Administración
                </a>
            </li>
            {% endif %}
            {% if estudio %}
            <li class="has_submenu ngreen">
                <a href="">
                    <!-- Menu name with icon -->
                    <i class="fa fa-file-text"></i> Estudio
                    <!-- Icon for dropdown -->
                    <span class="pull-right"><i class="fa fa-angle-right"></i></span>
                </a>
                <ul>
                    <li><a href="{%url 'mactor:lista_actores' estudio.id%}">Actores</a></li>
                    <li><a href="{% url 'mactor:lista_fichas' estudio.id%}">Estrategias</a></li>
                    <li><a href="{% url 'mactor:lista_objetivos' estudio.id%}">Objetivos</a></li>
                    <li><a href="{% url 'mactor:matriz_mid' estudio.id%}">Matriz de Influencias Directas</a></li>
                    <li><a href="{% url 'mactor:matriz_midi' estudio.id%}">Matriz de Influencias Directas e Indirectas</a></li>
                    <li><a href="{% url 'mactor:matriz_mao' estudio.id 1%}">Matriz 1MAO</a></li>
                    <li><a href="{% url 'mactor:matriz_mao' estudio.id 2%}">Matriz 2MAO</a></li>
                    <li><a href="{% url 'mactor:matriz_mao' estudio.id 3%}">Matriz 3MAO</a></li>
                    {% if usuario != 'EXPERTO'%}
                    <li><a href="{% url 'mactor:informe_final' estudio.id%}">Informe Final</a></li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}
        </ul>

    </div>
    {% endif %}
</div>