tecnicas/apps/mactor/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import listar_estudios, crearEstudio, editar_estudio, consultar_estudio,\
    crear_actor, listar_actores, editar_actor, consultar_actor, eliminar_actor, \
    crear_ficha, lista_fichas, editar_ficha, consultar_ficha, eliminar_ficha, consultar_ficha_mid, \
    crear_objetivo, listar_objetivos, editar_objetivo, consultar_objetivo, eliminar_objetivo, \
    crear_relacion_mid, generar_matriz_mid, generar_matriz_midi, generar_matriz_maxima, generar_matriz_ri, \
    generar_matriz_balance, generar_indicador_estabilidad, crear_1mao, crear_2mao, generar_matriz_mao,\
    generar_matrices_caa_daa, consultar_actores_faltantes, consultar_objetivos_faltantes, \
    crear_informe, exportar_estudio_xls, \
    histograma_mid, datos_histograma_mid, histograma_ri, datos_histograma_ri, \
    histograma_implicacion, histograma_movilizacion, datos_histogramas_mao,  \
    datos_histograma_caa_daa, histograma_caa_daa, \
    generar_mapa_midi, datos_mapa_midi, generar_mapa_caa_daa, datos_mapa_caa_daa, \
    generar_grafo_caa, datos_grafo_caa, generar_grafo_daa, datos_grafo_daa, \
    activar_consenso_influencias, activar_consenso_mao, activar_consenso_caa_daa

# nombre de la url, view que respondera y el parametro name
urlpatterns = [

    # Urls modelo Estudio_mactor
    url(r'^agregar_estudio/$', crearEstudio.as_view(), name='estudio'),
    url(r'^lista_estudios', login_required(listar_estudios), name='lista_estudios'),
    url(r'^editar_estudio/(?P<idEstudio>\d+)/$', login_required(editar_estudio), name='editar_estudio'),
    url(r'^consultar_estudio/$', login_required(consultar_estudio)),

    # Urls modelo Actor
    url(r'agregar_actor/$', login_required(crear_actor)),
    url(r'eliminar_actor/$', login_required(eliminar_actor)),
    url(r'editar_actor/$', login_required(editar_actor)),
    url(r'^lista_actores/(?P<idEstudio>\d+)/$', login_required(listar_actores), name='lista_actores'),
    url(r'consultar_actor', login_required(consultar_actor)),

    # Urls modelo Ficha
    url(r'^agregar_ficha/(?P<idEstudio>\d+)/$', login_required(crear_ficha), name='ficha'),
    url(r'eliminar_ficha/$', login_required(eliminar_ficha)),
    url(r'consultar_ficha/$', login_required(consultar_ficha)),
    url(r'^editar_ficha/(?P<idFicha>\d+)/$', login_required(editar_ficha), name='editar_ficha'),
    url(r'lista_fichas/(?P<idEstudio>\d+)/$', login_required(lista_fichas), name='lista_fichas'),
    url(r'consultar_ficha_mid/$', login_required(consultar_ficha_mid)),

    # Urls modelo Objetivo
    url(r'agregar_objetivo/$', login_required(crear_objetivo)),
    url(r'^lista_objetivos/(?P<idEstudio>\d+)/$', login_required(listar_objetivos), name='lista_objetivos'),
    url(r'eliminar_objetivo/$', login_required(eliminar_objetivo)),
    url(r'editar_objetivo/$', login_required(editar_objetivo)),
    url(r'consultar_objetivo', login_required(consultar_objetivo)),

    # Urls modelo Relacion_MID y matrices
    url(r'^agregar_influencia/(?P<idEstudio>\d+)/$', login_required(crear_relacion_mid), name='influencia'),
    url(r'^matriz_mid/(?P<idEstudio>\d+)/$', login_required(generar_matriz_mid), name='matriz_mid'),
    url(r'^matriz_midi/(?P<idEstudio>\d+)/$', login_required(generar_matriz_midi), name='matriz_midi'),
    url(r'^matriz_maxima/(?P<idEstudio>\d+)/$', login_required(generar_matriz_maxima), name='matriz_maxima'),
    url(r'^matriz_ri/(?P<idEstudio>\d+)/$', login_required(generar_matriz_ri), name='matriz_ri'),
    url(r'^matriz_balance/(?P<idEstudio>\d+)/$', login_required(generar_matriz_balance), name='matriz_balance'),
    url(r'^estabilidad/(?P<idEstudio>\d+)/$', login_required(generar_indicador_estabilidad), name='estabilidad'),

    # Urls modelo Relacion_MAO y matrices
    url(r'^1mao/(?P<idEstudio>\d+)/$', login_required(crear_1mao), name='1mao'),
    url(r'^2mao/(?P<idEstudio>\d+)/$', login_required(crear_2mao), name='2mao'),
    url(r'^matriz_mao/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matriz_mao), name='matriz_mao'),
    url(r'^matriz_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matrices_caa_daa), name='caa_daa'),

    # Urls consultas ajax
    url(r'mid-ajax/$', login_required(consultar_actores_faltantes)),  # obtiene lista actores X registrados en la mid
    url(r'mao-ajax/$', login_required(consultar_objetivos_faltantes)),  # obtiene lista objetivos X registrados en la mao

    # Urls histogramas de influencia
    url(r'^histograma_mid/(?P<idEstudio>\d+)/$', login_required(histograma_mid), name='histograma_mid'),
    url(r'datos_histograma_mid', login_required(datos_histograma_mid)),
    url(r'^histograma_ri/(?P<idEstudio>\d+)/$', login_required(histograma_ri), name='histograma_ri'),
    url(r'datos_histograma_ri', login_required(datos_histograma_ri)),

    # Urls histogramas mao
    url(r'^histograma_implicacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_implicacion),
        name='implicacion'),
    url(r'^histograma_movilizacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_movilizacion),
        name='movilizacion'),
    url(r'datos_histograma', login_required(datos_histogramas_mao)),

    # Urls mapa actores
    url(r'^mapa_actores/(?P<idEstudio>\d+)/$', login_required(generar_mapa_midi), name='mapa_actores'),
    url(r'datos_plano_midi', login_required(datos_mapa_midi)),

    # Urls graficos caa y daa
    url(r'^mapa_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_mapa_caa_daa), name='mapa_caa_daa'),
    url(r'datos_mapa_caa_daa', login_required(datos_mapa_caa_daa)),
    url(r'^histograma_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', histograma_caa_daa, name='hist_caa_daa'),
    url(r'datos_caa_daa', login_required(datos_histograma_caa_daa)),
    url(r'^grafo_caa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_caa), name='grafo_caa'),
    url(r'datos_grafo_caa', login_required(datos_grafo_caa)),
    url(r'^grafo_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_daa), name='grafo_daa'),
    url(r'datos_grafo_daa', login_required(datos_grafo_daa)),

    # Urls exportar a excel
    url(r'exportar_estudios/xls/(?P<idEstudio>\d+)/$', login_required(exportar_estudio_xls), name='estudios_xls'),

    # Urls consensos
    url(r'^consenso_influencias/(?P<idEstudio>\d+)/(?P<tipo>\d)/', login_required(activar_consenso_influencias), name='consenso_influencias'),
    url(r'^consenso_mao/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_mao), name='consenso_mao'),
    url(r'^consenso_caa_daa/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)/', login_required(activar_consenso_caa_daa), name='consenso_caa_daa'),

    # Urls modelo informe final
    url(r'^informe_final/(?P<idEstudio>\d+)/$', login_required(crear_informe), name='informe_final'),

]

tecnicas/tecnicas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    # urls vista administracion
    url(r'^admin/', admin.site.urls, ),
    # urls de la app mactor
    url(r'^mactor/', include('apps.mactor.urls', namespace="mactor")),
    # urls de la app entrevista
    url(r'^entrevista/', include('apps.entrevista.urls', namespace="entrevista")),
    # urls vista control de usuarios paquete Registration
    url(r'^accounts/', include('registration.backends.default.urls'))
]

tecnicas/apps/mactor/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

"""MODELO ESTUDIO MACTOR--------------------------------------------------------------------------------------------"""


class EstudioMactor(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    idAdministrador = models.ForeignKey(User, verbose_name='administrador', related_name='mactor_administrador')
    idCoordinador = models.ForeignKey(User, verbose_name='coordinador', related_name='mactor_coordinador')
    idExpertos = models.ManyToManyField(User, verbose_name='Expertos', related_name='mactor_expertos_set')
    fecha_inicio = models.DateField(default=now)
    fecha_final = models.DateField(default=now)
    estado = models.BooleanField(default=True)
    idProyecto = models.PositiveIntegerField(default=1)  # este campo junto con idAdministrador deben obtenerse mediante FK del modelo proyecto

# Definicion de nombre singular y plurar del modelo
    class Meta:
        verbose_name = 'Estudio_Mactor'
        verbose_name_plural = 'Estudios_Mactor'

# Campo a mostrar del modelo Estudio_Mactor (tabla en admin y listas desplegables)
    def __str__(self):
        return u'{0}'.format(self.titulo)


"""MODELO ACTOR-----------------------------------------------------------------------------------------------------"""


class Actor(models.Model):
    nombreLargo = models.CharField(max_length=50)
    nombreCorto = models.CharField(max_length=5)
    descripcion = models.TextField(max_length=500)
    idEstudio = models.ForeignKey(EstudioMactor, null=True, blank=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Actor'
        verbose_name_plural = 'Actores'

    def __str__(self):
        return u'{0} - {1}'.format(self.nombreCorto, self.nombreLargo)


"""MODELO FICHA DE ESTRATEGIAS--------------------------------------------------------------------------------------"""


class Ficha(models.Model):
    idActorY = models.ForeignKey(Actor, null=True, blank=False, related_name='mactor_actorY_ficha', on_delete=models.CASCADE)
    idActorX = models.ForeignKey(Actor, null=True, blank=False, related_name='mactor_actorX_ficha', on_delete=models.CASCADE)
    estrategia = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Ficha'
        verbose_name_plural = 'Fichas'
        # para evitar que la pareja de registros se repita en ese mismo orden
        unique_together = ('idActorY', 'idActorX')

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idActorX, self.idActorY, self.estrategia)


"""MODELO OBJETIVO--------------------------------------------------------------------------------------------------"""


class Objetivo(models.Model):
    nombreLargo = models.CharField(max_length=50)
    nombreCorto = models.CharField(max_length=5)
    descripcion = models.TextField(max_length=500)
    idEstudio = models.ForeignKey(EstudioMactor, null=True, blank=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Objetivo'
        verbose_name_plural = 'Objetivos'

    def __str__(self):
        return u'{0} - {1}'.format(self.nombreCorto, self.nombreLargo)


"""MODELO RELACIONES DE INFLUENCIA DIRECTA---------------------------------------------------------------------------"""


class RelacionMID(models.Model):
    idActorX = models.ForeignKey(Actor, null=True, blank=False, related_name='mactor_actorX_set', on_delete=models.CASCADE)
    idActorY = models.ForeignKey(Actor, null=True, blank=False, related_name='mactor_actorY_set', on_delete=models.CASCADE)
    valor = models.IntegerField()
    justificacion = models.TextField()
    idExperto = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = 'Relacion_de_Influencia'
        verbose_name_plural = 'Relaciones_de_influencia'
        # para evitar que la pareja de registros se repita en ese mismo orden
        unique_together = ('idActorX', 'idActorY', 'idExperto')

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idActorY, self.idActorX, self.valor)


"""MODELO RELACIONES DE ACTOR x OBJETIVO---------------------------------------------------------------------------"""


class RelacionMAO(models.Model):
    tipo = models.IntegerField(null=True, blank=True)
    idActorY = models.ForeignKey(Actor, null=False, blank=False, on_delete=models.CASCADE)
    idObjetivoX = models.ForeignKey(Objetivo, null=False, blank=False, on_delete=models.CASCADE)
    valor = models.IntegerField()
    justificacion = models.TextField()
    idExperto = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = 'Relacion_MAO'
        verbose_name_plural = 'Relaciones_MAO'
        unique_together = ('tipo', 'idActorY', 'idObjetivoX', 'idExperto')

    def __str__(self):
        return u'{0} - {1} - {2} - {3} - {4} - {5}'.format(self.tipo, self.idActorY, self.idObjetivoX, self.valor, self.idExperto)


"""MODELO INFORME FINAL---------------------------------------------------------------------------------------------"""


class InformeFinal(models.Model):
    fecha = models.DateTimeField(auto_now=True)
    informe = models.TextField()
    estado = models.BooleanField(default=False)
    idEstudio = models.ForeignKey(EstudioMactor)

    class Meta:
        verbose_name = 'Informe_final'
        verbose_name_plural = 'Informes_finales'

    def __str__(self):
        return u'{0} - {1} - {2}'.format(self.idEstudio, self.fecha, self.informe, self.estado)

tecnicas/apps/mactor/templates/influencia/crear_influencia.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
	{% if usuario != '' %}
		<input hidden class="col-sm-1" type="number" name="idEstudio" value="{{estudio.id}}">Estudio: {{estudio.titulo}}
	{% endif %}
{% endblock %}

{% block content %}

{% if usuario != '' and usuario != 'COORDINADOR' %}
<div class="matter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="widget wgreen">
					<div class="widget-head">
						<div class="pull-left">Formulario de Influencias Directas</div>
						<div class="pull-right">{{porcentaje}}% Diligenciado</div>
						<div class="clearfix"></div>
					</div>
					<div class="widget-content">
						<div class="padd">
							<hr />
							<!-- Form starts-->
							<form class="form-horizontal" role="form" method="post" id="form_mid">
								{% csrf_token %}
								<div class="row">
									<div class="col-md-7 col-md-offset-1">
										<div class="form-group">
											{{form.idActorY.errors}}
											<label class="control-label" style="text-align: left">Influencia del actor</label>
											<select name="idActorY" class="form-control" required id="id_idActorY">
												{% if estudio.estado is True %}
													{% if actores %}
														<option value="" selected>----Seleccionar----</option>
														{% for actor in actores %}
															<option value="{{actor.id}}">{{actor.nombreCorto}} - {{actor.nombreLargo}}</option>
														{% endfor %}
													{% else %}
												<option value="" selected>----NO SE HAN REGISTRADO ACTORES EN ESTE ESTUDIO----</option>
													{% endif %}
												{% else %}
												<option value="" selected>----EL PRESENTE ESTUDIO NO ESTA HABILITADO----</option>
												{% endif %}
											</select>
										</div>
									</div>
								</div>

								<!--DIV descripcion del actorY-->
								<div class="row">
									<div class="col-md-7 col-md-offset-1">
										<div id="info" style='text-align: justify'></div>
									</div>
								</div>

                                <div class="row">
                                    <div class="col-md-7 col-md-offset-1">
                                        <div class="form-group">
                                            {{form.idActorX.errors}}
                                            <label class="control-label" style="text-align: left">Sobre el actor</label>
                                            <select name="idActorX" class="form-control" required id="id_idActorX">
                                                {% if estudio.estado is True %}
                                                    {% if actores %}
                                                        <option value="" selected>----Seleccionar----</option>
                                                        {% for actor in actores %}
                                                            <option value="{{actor.id}}">{{actor.nombreCorto}} - {{actor.nombreLargo}}</option>
                                                        {% endfor %}
                                                    {% else %}
                                                    <option value="" selected>----NO SE HAN REGISTRADO ACTORES EN ESTE ESTUDIO----</option>
                                                    {% endif %}
                                                {% else %}
                                                    <option value="" selected>----EL PRESENTE ESTUDIO NO ESTA HABILITADO----</option>
                                                {% endif %}
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-md-2 col-md-offset-1">
                                        <div class="form-group">
                                            <label class="control-label" style="text-align: left">Valor</label>
                                            <br>
                                            {{form.valor}}
                                        </div>
                                    </div>
                                </div>

                                <!--Div descripcion del actorX-->
                                <div class="row">
                                    <div class="col-md-7 col-md-offset-1">
                                        <div id="info2" style='text-align: justify'></div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-7 col-md-offset-1">
                                        <div class="form-group">
                                            <label class="control-label" style="text-align: left">Justificación</label>
                                            {{form.justificacion}}
                                        </div>
                                    </div>
                                </div>

                                <div  class="row">
                                    <div class="col-md-3 col-md-offset-1" hidden>
                                        <div class="form-group">
                                            <label class="control-label" style="text-align: left">Experto</label>
                                            <input class="form-control" type="text" value="{{user.id}}" name="idExperto">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-8">
                                            <a class="btn btn-sm btn-success" href="{%url 'mactor:lista_objetivos' estudio.id%}" title="Lista de objetivos"><i class="fa fa-arrow-left"></i> Objetivos</a>
                                            <button type="submit" class="btn btn-primary" title="Guardar"><i class="fa fa-plus"></i> Guardar</button>
                                            <a class="btn btn-primary" data-toggle="modal" href="#myModal" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                                            {% if actores %}
                                                <a class="btn btn-primary" data-toggle="modal" href="#myModal2" onclick="Consultar_ficha()" title="Consultar estrategias"><i class="fa fa-eye"></i> Consultar</a>
                                            {% endif %}
                                            <a class="btn btn-sm btn-success" href="{% url 'mactor:matriz_mid' estudio.id%}" title="Matriz MID">Matriz MID <i class="fa fa-arrow-right"></i></a>
                                        </div>
                                    </div>
                                </div>

                            </form>

<!--INICIO MODALS---------------------------"-->
				{% include 'influencia/modals_influencia.html'%}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
	{% else %}
		<img src="{% static 'img/acceso_denegado.png' %}">
		<h2>Upps...no cuenta con en este estudio.</h2>
	{% endif %}

{% block extrajs %}
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/js_mactor/consultar_desc_actor.js' %}"></script>
<script src="{% static 'js/js_mactor/consultar_ficha_mid.js' %}"></script>
<script src="{% static 'js/js_mactor/desactivar_opciones_select.js' %}"></script>
{% endblock %}

<!--Desactiva el segundo select hasta que se seleccione una opcion en el primero-->
<script type="text/javascript">
	document.getElementById("id_idActorX").disabled = true;
</script>

{% endblock %}

tecnicas/apps/mactor/templates/influencia/matriz_midi.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
    {% if usuario != '' %}
        <input hidden class="col-sm-1" type="number" name="idEstudio" value="{{estudio.id}}">Estudio: {{estudio.titulo}}
    {% endif %}
{% endblock %}

{% block content %}
    {% if usuario != '' and usuario != 'COORDINADOR' %}

        <!--MATRIZ MIDI------------------------------------------------------------------------------------------------->
        <div class="container">
                <div class="row">
                    <div class="col-md-10">
                        <div class="widget wgreen">
                            <div class="widget-head">
                                <div class="pull-left">MIDI - Matriz de Influencias Directas e Indirectas</div>
                                <div class="widget-icons pull-right">
                                    {% if valores_midi %}
                                     <select name="graficos_midi" class="form-control" onchange="location = this.value;">
                                        <option value="">Análisis MIDI</option>
                                        <option value="{% url 'mactor:mapa_actores' estudio.id %}">Mapa de actores</option>
                                        <option value="{% url 'mactor:matriz_ri' estudio.id %}">Coeficiente de fuerza Ri</option>
                                        <option value="{% url 'mactor:estabilidad' estudio.id %}">Coeficiente de estabilidad H</option>
                                         {% if usuario == 'COORDINADOR_EXPERTO' %}
                                        <option value="{% url 'mactor:consenso_influencias' estudio.id 2 %}">Consenso MIDI</option>
                                         {% endif %}
                                     </select>
                                    {% endif %}
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="widget-content">
                                <table class="table table-bordered" id="tabla2">
                                    <thead>
                                        <tr>
                                            {% if actores and valores_midi %}
                                                <input style='text-align: center;'  type="text" size="4" readonly value="">
                                                    {% for actor in actores %}
                                                        <input id="act{{actor.id}}" style='text-align: center; background-color: #5e5e5e; color: white' readonly type="text"
                                                               title="{{actor.nombreLargo|upper}}" size="4"
                                                               value="{{actor.nombreCorto}}" data-toggle="modal"
                                                               href="#modal_Consultar_actor">
                                                    {% endfor %}
                                                <input style='text-align: center; background-color: #5e5e5e; color: white' readonly  type="text" size="4" title="INFLUENCIA DIRECTA E INDIRECTA" value="I.DI">
                                            {% endif %}
                                            <br>
                                         </tr>
                                    </thead>
                                    <tbody>
                                    {%if valores_midi %}
                                    <tr>
                                        {% for i in valores_midi %}
                                            <!--Inserta el ultimo valor antes del salto de linea-->
                                            {% if i.posicion == posicion_salto %}
                                                <input style='text-align: center;' readonly type="text" size="4" value="{{i.valor}}" title="{{i.descripcion}}">
                                                <br>

                                            <!--Inserta los nombres cortos en el eje Y-->
                                            {% elif i.posicion == 0 %}
                                                {% if i.valor != 'D.DI' %}
                                                    <input id="mid{{i.valor}}" style='text-align: center; background-color: #5e5e5e; color: white ' readonly type="text" size="4"
                                                           title="{{i.descripcion|upper}}" value="{{i.valor}}"
                                                           data-toggle="modal" href="#modal_Consultar_actor">
                                                {% else %}
                                                    <input style='text-align: center; background-color: #5e5e5e; color: white ' readonly type="text" size="4" title="{{i.descripcion|upper}}"
                                                           value="{{i.valor}}">
                                                {% endif %}

                                            <!--Inserta los valores ubicados entre la primera y ultima celda-->
                                            {% else %}
                                                <input style='text-align: center;' readonly type="text" size="4" value="{{i.valor}}" title="{{i.descripcion}}">
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <h3>Finalice el registro de las influencias directas para visualizar la matriz MIDI.</h3>
                                    {% endif %}
                                            <br>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        <!--BOTONES---------------------------------------------------------------------------------------------------->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-8">
                <a class="btn btn-sm btn-success" href="{% url 'mactor:matriz_mid' estudio.id %}" title="Matriz MID"><i class="fa fa-arrow-left"></i> Atrás</a>
                <a class="btn btn-primary" data-toggle="modal" href="#myModal" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                <a class="btn btn-primary" href="{% url 'mactor:matriz_maxima' estudio.id %}" title="Matriz Máxima"><i class="fa fa-table"></i> MAX</a>
                <a class="btn btn-primary" href="{% url 'mactor:matriz_balance' estudio.id %}" title="Matriz de Balance Líquido"><i class="fa fa-table"></i> BL</a>
            </div>
        </div>

        <!--INICIO MODAL CONSULTAR ACTOR------------------------------------------------------------------------------->

                    {% include 'actor/modal_detalle_actor.html' %}

        <!--INICIO MODAL AYUDA----------------------------------------------------------------------------------------->

        <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
                        <h4 class="modal-title">Ayuda -  Matriz MIDI</h4>
                    </div>
                    <div class="modal-body" style="text-align: justify">
                        <p>La Matriz de Influencias Directas e Indirectas (MIDI), calculada a partir de MID, permite
                            tener en cuenta en el análisis la influencia que los actores reciben de forma indirecta, ya
                            que un actor puede afectar a otro actuando sobre un tercero.
                        </p>
                        <br>
                        <p>La columna Influencia Directa e Indirecta (I.DI), representa la influencia total (directa e
                            indirecta) que el actor ejerce en el grupo de actores estudiado. Mientras que la fila
                            Dependencia Directa e Indirecta (D.DI), la influencia total que el resto de actores ejerce
                            sobre ese actor.
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <img src="{% static 'img/acceso_denegado.png' %}">
        <h2>Upps...no cuenta con permisos en este estudio.</h2>
    {% endif %}
{% block extrajs %}
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/js_mactor/js_mactor_modals/consultar/consultar_actor_objetivo_matriz.js'%}"></script>
{% endblock %}

{% endblock %}