tecnicas/apps/mactor/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import listar_estudios, crearEstudio, editar_estudio, consultar_estudio,\
    crear_actor, listar_actores, editar_actor, consultar_actor, eliminar_actor, \
    crear_ficha, lista_fichas, editar_ficha, consultar_ficha, eliminar_ficha, consultar_ficha_mid, \
    crear_objetivo, listar_objetivos, editar_objetivo, consultar_objetivo, eliminar_objetivo, \
    crear_relacion_mid, generar_matriz_mid, generar_matriz_midi, generar_matriz_maxima, generar_matriz_ri, \
    generar_matriz_balance, generar_indicador_estabilidad, crear_1mao, crear_2mao, generar_matriz_mao,\
    generar_matrices_caa_daa, consultar_actores_faltantes, consultar_objetivos_faltantes, \
    crear_informe, exportar_estudio_xls, \
    histograma_mid, datos_histograma_mid, histograma_ri, datos_histograma_ri, \
    histograma_implicacion, histograma_movilizacion, datos_histogramas_mao,  \
    datos_histograma_caa_daa, histograma_caa_daa, \
    generar_mapa_midi, datos_mapa_midi, generar_mapa_caa_daa, datos_mapa_caa_daa, \
    generar_grafo_caa, datos_grafo_caa, generar_grafo_daa, datos_grafo_daa, \
    activar_consenso_influencias, activar_consenso_mao, activar_consenso_caa_daa

# nombre de la url, view que respondera y el parametro name
urlpatterns = [

    # Urls modelo Estudio_mactor
    url(r'^agregar_estudio/$', crearEstudio.as_view(), name='estudio'),
    url(r'^lista_estudios', login_required(listar_estudios), name='lista_estudios'),
    url(r'^editar_estudio/(?P<idEstudio>\d+)/$', login_required(editar_estudio), name='editar_estudio'),
    url(r'^consultar_estudio/$', login_required(consultar_estudio)),

    # Urls modelo Actor
    url(r'agregar_actor/$', login_required(crear_actor)),
    url(r'eliminar_actor/$', login_required(eliminar_actor)),
    url(r'editar_actor/$', login_required(editar_actor)),
    url(r'^lista_actores/(?P<idEstudio>\d+)/$', login_required(listar_actores), name='lista_actores'),
    url(r'consultar_actor', login_required(consultar_actor)),

    # Urls modelo Ficha
    url(r'^agregar_ficha/(?P<idEstudio>\d+)/$', login_required(crear_ficha), name='ficha'),
    url(r'eliminar_ficha/$', login_required(eliminar_ficha)),
    url(r'consultar_ficha/$', login_required(consultar_ficha)),
    url(r'^editar_ficha/(?P<idFicha>\d+)/$', login_required(editar_ficha), name='editar_ficha'),
    url(r'lista_fichas/(?P<idEstudio>\d+)/$', login_required(lista_fichas), name='lista_fichas'),
    url(r'consultar_ficha_mid/$', login_required(consultar_ficha_mid)),

    # Urls modelo Objetivo
    url(r'agregar_objetivo/$', login_required(crear_objetivo)),
    url(r'^lista_objetivos/(?P<idEstudio>\d+)/$', login_required(listar_objetivos), name='lista_objetivos'),
    url(r'eliminar_objetivo/$', login_required(eliminar_objetivo)),
    url(r'editar_objetivo/$', login_required(editar_objetivo)),
    url(r'consultar_objetivo', login_required(consultar_objetivo)),

    # Urls modelo Relacion_MID y matrices
    url(r'^agregar_influencia/(?P<idEstudio>\d+)/$', login_required(crear_relacion_mid), name='influencia'),
    url(r'^matriz_mid/(?P<idEstudio>\d+)/$', login_required(generar_matriz_mid), name='matriz_mid'),
    url(r'^matriz_midi/(?P<idEstudio>\d+)/$', login_required(generar_matriz_midi), name='matriz_midi'),
    url(r'^matriz_maxima/(?P<idEstudio>\d+)/$', login_required(generar_matriz_maxima), name='matriz_maxima'),
    url(r'^matriz_ri/(?P<idEstudio>\d+)/$', login_required(generar_matriz_ri), name='matriz_ri'),
    url(r'^matriz_balance/(?P<idEstudio>\d+)/$', login_required(generar_matriz_balance), name='matriz_balance'),
    url(r'^estabilidad/(?P<idEstudio>\d+)/$', login_required(generar_indicador_estabilidad), name='estabilidad'),

    # Urls modelo Relacion_MAO y matrices
    url(r'^1mao/(?P<idEstudio>\d+)/$', login_required(crear_1mao), name='1mao'),
    url(r'^2mao/(?P<idEstudio>\d+)/$', login_required(crear_2mao), name='2mao'),
    url(r'^matriz_mao/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matriz_mao), name='matriz_mao'),
    url(r'^matriz_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/', login_required(generar_matrices_caa_daa), name='caa_daa'),

    # Urls consultas ajax
    url(r'mid-ajax/$', login_required(consultar_actores_faltantes)),  # obtiene lista actores X registrados en la mid
    url(r'mao-ajax/$', login_required(consultar_objetivos_faltantes)),  # obtiene lista objetivos X registrados en la mao

    # Urls histogramas de influencia
    url(r'^histograma_mid/(?P<idEstudio>\d+)/$', login_required(histograma_mid), name='histograma_mid'),
    url(r'datos_histograma_mid', login_required(datos_histograma_mid)),
    url(r'^histograma_ri/(?P<idEstudio>\d+)/$', login_required(histograma_ri), name='histograma_ri'),
    url(r'datos_histograma_ri', login_required(datos_histograma_ri)),

    # Urls histogramas mao
    url(r'^histograma_implicacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_implicacion),
        name='implicacion'),
    url(r'^histograma_movilizacion/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(histograma_movilizacion),
        name='movilizacion'),
    url(r'datos_histograma', login_required(datos_histogramas_mao)),

    # Urls mapa actores
    url(r'^mapa_actores/(?P<idEstudio>\d+)/$', login_required(generar_mapa_midi), name='mapa_actores'),
    url(r'datos_plano_midi', login_required(datos_mapa_midi)),

    # Urls graficos caa y daa
    url(r'^mapa_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', login_required(generar_mapa_caa_daa), name='mapa_caa_daa'),
    url(r'datos_mapa_caa_daa', login_required(datos_mapa_caa_daa)),
    url(r'^histograma_caa_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)/$', histograma_caa_daa, name='hist_caa_daa'),
    url(r'datos_caa_daa', login_required(datos_histograma_caa_daa)),
    url(r'^grafo_caa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_caa), name='grafo_caa'),
    url(r'datos_grafo_caa', login_required(datos_grafo_caa)),
    url(r'^grafo_daa/(?P<idEstudio>\d+)/(?P<numero_matriz>\d)$', login_required(generar_grafo_daa), name='grafo_daa'),
    url(r'datos_grafo_daa', login_required(datos_grafo_daa)),

    # Urls exportar a excel
    url(r'exportar_estudios/xls/(?P<idEstudio>\d+)/$', login_required(exportar_estudio_xls), name='estudios_xls'),

    # Urls consensos
    url(r'^consenso_influencias/(?P<idEstudio>\d+)/(?P<tipo>\d)/', login_required(activar_consenso_influencias), name='consenso_influencias'),
    url(r'^consenso_mao/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)', login_required(activar_consenso_mao), name='consenso_mao'),
    url(r'^consenso_caa_daa/(?P<idEstudio>\d+)/(?P<matriz>\d)/(?P<tipo>\d)/', login_required(activar_consenso_caa_daa), name='consenso_caa_daa'),

    # Urls modelo informe final
    url(r'^informe_final/(?P<idEstudio>\d+)/$', login_required(crear_informe), name='informe_final'),

]

tecnicas/tecnicas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    # urls vista administracion
    url(r'^admin/', admin.site.urls, ),
    # urls de la app mactor
    url(r'^mactor/', include('apps.mactor.urls', namespace="mactor")),
    # urls de la app entrevista
    url(r'^entrevista/', include('apps.entrevista.urls', namespace="entrevista")),
    # urls vista control de usuarios paquete Registration
    url(r'^accounts/', include('registration.backends.default.urls'))
]

tecnicas/apps/mactor/views.py
import xlwt
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .constants import VALOR_RELACION_NO_REGISTRADA, MATRIZ_COMPLETA, MATRIZ_INCOMPLETA
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import JsonResponse, HttpResponse, request, Http404
from django.views.generic import CreateView
from .models import *
from .forms import *

""" ----------------------------------------VIEWS MODELO ESTUDIO MACTOR---------------------------------"""


class crearEstudio(CreateView):
    model = EstudioMactor
    form_class = FormEstudio
    template_name = 'estudio/crear_estudio_mactor.html'
    success_url = reverse_lazy('mactor:lista_estudios')


def listar_estudios(request):

    estudios = EstudioMactor.objects.all().order_by('-estado', 'titulo')
    estudios_usuario = []

    for i in estudios:
        estudio = EstudioMactor.objects.get(id=i.id)
        lista_expertos = estudio.idExpertos.all()
        if request.user in lista_expertos or request.user == i.idCoordinador or request.user == i.idAdministrador:
            estudios_usuario.append(i)

    page = request.GET.get('page', 1)
    paginator = Paginator(estudios_usuario, 10)
    try:
        estudio_contexto = paginator.page(page)
    except PageNotAnInteger:
        estudio_contexto = paginator.page(1)
    except EmptyPage:
        estudio_contexto = paginator.page(paginator.num_pages)

    contexto = {'lista_estudios': estudio_contexto}
    return render(request, 'estudio/lista_estudios.html', contexto)


def consultar_estudio(request):

    if request.is_ajax():
        estudio = get_object_or_404(EstudioMactor, id=int(request.GET['id']))
        response = JsonResponse({'titulo': estudio.titulo, 'descripcion': estudio.descripcion})
        return HttpResponse(response.content)
    else:
        return redirect('/')


def editar_estudio(request, idEstudio):

    estudio = get_object_or_404(EstudioMactor, id=int(idEstudio))
    informes = InformeFinal.objects.all().order_by('idEstudio')
    flag = False

    for informe in informes:
        if informe.idEstudio.id == int(idEstudio) and informe.estado is True:
            flag = True
           
    if request.method == 'GET':
        form = FormEstudio(instance=estudio)
    else:
        form = FormEstudio(request.POST, instance=estudio)
        if form.is_valid():
            form.save()
            return redirect('mactor:lista_estudios')
    return render(request, 'estudio/editar_estudio.html', {'form': form, 'informe': flag, 'estudio': estudio})

"""-------------------------------------------VIEWS MODELO ACTOR---------------------------------------"""


def crear_actor(request):

    nombreLargo = request.GET['nombreLargo']
    nombreCorto = request.GET['nombreCorto']
    descripcion = request.GET['descripcion']
    estudio = get_object_or_404(EstudioMactor, id=int(request.GET['codigo_Estudio']))
    actores = Actor.objects.filter(idEstudio=estudio.id)
    flag = False

    for actor in actores:
        if actor.nombreCorto == nombreCorto:
            flag = True

    if flag is False:
        try:
            actor = Actor(nombreLargo=nombreLargo, nombreCorto=nombreCorto, descripcion=descripcion, idEstudio=estudio)
            actor.save()
            response = JsonResponse({'info': "El actor " + nombreLargo + " se ha registrado con exito"})
            return HttpResponse(response.content)
        except:
            response = JsonResponse({'info': "ERROR - El actor no pudo ser agregado."})
            return HttpResponse(response.content)
    else:
        response = JsonResponse({'info': "Ya existe un actor con el nombre corto " + nombreCorto})
        return HttpResponse(response.content)


def editar_actor(request):

    if request.is_ajax():
        id = request.GET.get('id')
        nombreLargo = request.GET.get('nombreLargo')
        nombreCorto = request.GET.get('nombreCorto')
        descripcion = request.GET.get('descripcion')
        idEstudio = int(request.GET.get('idEstudio'))

        # se obtiene de los actores exceptuando el que se va a modificar para comparar
        actores = Actor.objects.all().filter(idEstudio=idEstudio).exclude(id=id)
        flag = False

        # se verifica que el nombre corto modificado no coincida con el de otros actores
        for actor in actores:
            if actor.nombreCorto == nombreCorto:
                flag = True

        # se realiza la modificacion de los datos y se envia la respuesta
        if flag is False:
            try:
                actor = get_object_or_404(Actor, id=id, idEstudio=idEstudio)
                actor.nombreLargo = nombreLargo
                actor.nombreCorto = nombreCorto
                actor.descripcion = descripcion
                actor.save()
                mensaje = "El registro del actor " + nombreLargo + " se ha actualizado con exito"
                response = JsonResponse({'info': mensaje})
                return HttpResponse(response.content)
            except:
                mensaje = "Error: no se pudo modificar"
                response = JsonResponse({'info': mensaje})
                return HttpResponse(response.content)
        else:
            mensaje = "Ya existe un actor con el nombre corto " + nombreCorto
            response = JsonResponse({'info': mensaje})
            return HttpResponse(response.content)


def consultar_actor(request):

    if request.is_ajax():
        id = request.GET.get('id')
        idEstudio = request.GET['idEstudio']

        # busqueda por nombre corto
        if id.count("mid") or id.count("caa") or id.count("daa"):
            id = id[3:]
            actor = get_object_or_404(Actor, nombreCorto=id, idEstudio=int(idEstudio))
        # busqueda por id con subcadena
        elif id.count("act") or id.count("ver"):
            id = id[3:]
            actor = get_object_or_404(Actor, id=id)
        # busqueda por id
        else:
            id = int(id)
            actor = get_object_or_404(Actor, id=id)

        response = JsonResponse(
            {'nombreCorto': actor.nombreCorto,
             'nombreLargo': actor.nombreLargo,
             'descripcion': actor.descripcion})
        return HttpResponse(response.content)
    else:
        return redirect('/')        # redirecciona a la misma pagina


def listar_actores(request, idEstudio):

    estudio = get_object_or_404(EstudioMactor, id=int(idEstudio))
    actores = Actor.objects.filter(idEstudio=estudio.id).order_by('nombreLargo')
    tipo_usuario = obtener_tipo_usuario(request, idEstudio)
    contexto = {'estudio': estudio,
                'usuario': tipo_usuario,
                'lista_actores': actores,
                'cantidad_registrados': len(actores)}
    return render(request, 'actor/lista_actores.html', contexto)


def eliminar_actor(request):

    if request.is_ajax():
        actor = Actor.objects.get(id=request.GET.get('id'))
        try:
            actor.delete()
            response = JsonResponse({'info': "Actor "+actor.nombreLargo + " eliminado con exito"})
            return HttpResponse(response.content)
        except:
            response = JsonResponse({'info': "El actor "+actor.nombreLargo + "no pudo ser eliminado"})
            return HttpResponse(response.content)


""" -------------------------------------------VIEWS MODELO FICHA ACTOR-----------------------------------"""


def crear_ficha(request, idEstudio):

    estudio = get_object_or_404(EstudioMactor, id=int(idEstudio))
    tipo_usuario = obtener_tipo_usuario(request, estudio.id)
    if request.method == 'POST':
        form = FormFicha(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mactor:lista_fichas', estudio.id)
    else:
        actores = Actor.objects.filter(idEstudio=estudio.id).order_by('nombreLargo')
        form = FormFicha()
    return render(request, 'ficha/crear_ficha.html', {'form': form, 'estudio': estudio, 'usuario': tipo_usuario,
                                                      'actores': actores})


def lista_fichas(request, idEstudio):

    estudio = get_object_or_404(EstudioMactor, id=int(idEstudio))
    fichas = Ficha.objects.filter(idActorY__idEstudio=estudio.id).order_by('idActorY', 'idActorX')
    tipo_usuario = obtener_tipo_usuario(request, estudio.id)

    page = request.GET.get('page', 1)
    paginator = Paginator(fichas, 15)
    try:
        fichas_contexto = paginator.page(page)
    except PageNotAnInteger:
        fichas_contexto = paginator.page(1)
    except EmptyPage:
        fichas_contexto = paginator.page(paginator.num_pages)

    contexto = {'estudio': estudio, 'usuario': tipo_usuario, 'lista_fichas': fichas_contexto}
    return render(request, 'ficha/lista_fichas.html', contexto)


def editar_ficha(request, idFicha):

    ficha = get_object_or_404(Ficha, id=int(idFicha))
    estudio = get_object_or_404(EstudioMactor, id=ficha.idActorY.idEstudio.id)
    tipo_usuario = obtener_tipo_usuario(request, estudio.id)
    actores = [Actor.objects.get(id=ficha.idActorY.id), Actor.objects.get(id=ficha.idActorX.id)]

    if request.method == 'GET':
        form = FormFicha(instance=ficha)
    else:
        form = FormFicha(request.POST, instance=ficha)
        if form.is_valid():
            form.save()
            return redirect('mactor:lista_fichas', estudio.id)
    return render(request, 'ficha/editar_ficha.html', {'form': form, 'actores': actores, 'estudio': estudio,
                                                       'usuario': tipo_usuario})


def consultar_ficha(request):

    if request.is_ajax():
        id = request.GET['id']
        ficha = get_object_or_404(Ficha, id=int(id))
        actorY = ficha.idActorY.nombreLargo
        actorX = ficha.idActorX.nombreLargo
        response = JsonResponse({'actorY': actorY, 'actorX': actorX, 'estrategia': ficha.estrategia})
        return HttpResponse(response.content)

tecnicas/apps/mactor/templates/mao/consenso/consenso_1mao.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
    {% if usuario != '' %}
        <input hidden class="col-sm-1" type="number" name="idEstudio" value="{{estudio.id}}">Estudio: {{estudio.titulo}}
    {% endif %}
{% endblock %}

{% block content %}
    {% if usuario != '' and usuario != 'EXPERTO' %}
        <!--Matriz 1MAO-------------------------------------------------------------------------------------------------->
        <div class="container">
                <div class="row">
                    <div class="col-md-10">
                        <div class="widget wblue">
                            <div class="widget-head">
                                 <div class="pull-left">Consenso - Matriz de Posiciones Simples 1MAO</div>
                                <div class="widget-icons pull-right">
                                    <select name="idObjetivoX" class="form-control" onchange="location = this.value;">
                                        <option value="">Análisis consenso</option>
                                        <option value="{% url 'mactor:consenso_mao' estudio.id 1 4%}">Histograma de Implicaciones</option>
                                        <option value="{% url 'mactor:consenso_mao' estudio.id 1 5%}">Histograma de Movilizaciones</option>
                                    </select>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="widget-content">
                                    {% include 'mao/table_matriz_mao.html' %}
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        {% if expertos %}
            <p><h5>Expertos en consenso = {{expertos}}</h5></p>
        {% else %}
            <p><h5>Ningún experto ha finalizado la matriz 1MAO</h5></p>
        {% endif %}
        <br>


        <!--BOTONES----------------------------------------------------------------------------------------------------->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-8">
                {% if usuario == 'COORDINADOR_EXPERTO' %}
                <a class="btn btn-sm btn-success" href="{% url 'mactor:matriz_mao' estudio.id 1%}" title="Atrás"><i class="fa fa-arrow-left"></i> Atrás</a>
                {% else %}
                <a class="btn btn-sm btn-success" href="{% url 'mactor:matriz_mid' estudio.id %}" title="Matriz de Influencias Directas"><i class="fa fa-arrow-left"></i> Matriz MID</a>
                {% endif %}
                <a class="btn btn-primary" data-toggle="modal" href="#myModal" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                <a class="btn btn-primary" id="caa_daa" href="{%url 'mactor:consenso_caa_daa' estudio.id 1 1%}" title=" Consenso Matrices de convergencia y divergencia"><i class="fa fa-table"></i> CAA-DAA</a>
                <a class="btn btn-sm btn-success" href="{% url 'mactor:matriz_mao' estudio.id 2%}" title="Matriz Valorada de Posiciones">Matriz 2MAO <i class="fa fa-arrow-right"></i></a>
            </div>
        </div>

        <!--INICIO MODAL CONSULTAR ACTOR Y OBJETIVO--------------------------------------------------------------------->

                    {% include 'actor/modal_detalle_actor.html' %}

                    {% include 'objetivo/modal_detalle_objetivo.html' %}


        <!--MODAL AYUDA------------------------------------------------------------------------------------------>

                    <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title">Ayuda - Matriz de Posiciones Simples (1MAO)</h4>
                                </div>
                                <div class="modal-body" style="text-align: justify">
                                    <p>La matriz 1MAO describe la actitud actual de cada actor
                                        en relación a cada objetivo, indicando su posición a favor (+1), en contra (-1) o
                                        neutra (0) hacia el alcance de cada objetivo (Arcade, Godet, Meunier, & Roubelat, 2004).</p><br>

                                    <p>De acuerdo a Castro y Perestrelo (2000):<br>
                                        <i class="fa fa-check"></i> La suma en fila, indica el grado de implicación de cada actor en los objetivos
                                        estudiados, es decir, el número de objetivos para los que cada actor tiene una
                                        posición activa, concordante o discordante.<br>

                                        <i class="fa fa-check"></i> La suma en columna indica el grado de movilización de los objetivos, es decir,
                                        el número de actores que tienen una posición activa, de acuerdo o desacuerdo,
                                        para cada objetivo.
                                    </p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                                </div>
                            </div>
                        </div>
                    </div>
    {% else %}
        <img src="{% static 'img/acceso_denegado.png' %}">
        <h2>Upps...no cuenta con los permisos necesarios para acceder a esta página.</h2>
    {% endif %}

{% block extrajs %}
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/js_mactor/js_mactor_modals/consultar/consultar_actor_objetivo_matriz.js'%}"></script>
{% endblock %}

{% endblock %}

tecnicas/apps/mactor/templates/mao/consenso/consenso_3mao.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
    {% if usuario != '' %}
        <input hidden class="col-sm-1" type="number" name="idEstudio" value="{{estudio.id}}">Estudio: {{estudio.titulo}}
    {% endif %}
{% endblock %}

{% block content %}
    {% if usuario != '' and usuario != 'EXPERTO' %}
        <!--Matriz 3MAO-------------------------------------------------------------------------------------------------->
        <div class="container">
                <div class="row">
                    <div class="col-md-10">
                        <div class="widget wblue">
                            <div class="widget-head">
                                 <div class="pull-left">Consenso - Matriz Valorada y Ponderada de Posiciones 3MAO</div>
                                <div class="widget-icons pull-right">
                                    <select name="histogramas" class="form-control" onchange="location = this.value;">
                                        <option value="">Análisis consenso</option>
                                        <option value="{% url 'mactor:consenso_mao' estudio.id 3 4 %}">Histograma de Implicaciones</option>
                                        <option value="{% url 'mactor:consenso_mao' estudio.id 3 5 %}">Histograma de Movilizaciones</option>
                                    </select>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="widget-content">
                                {% include 'mao/table_matriz_mao.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        {% if expertos %}
            <p><h5>Expertos en consenso = {{expertos}}</h5></p>
        {% else %}
            <p><h5>Ningún experto ha finalizado la matriz MID y 2MAO.</h5></p>
        {% endif %}
        <br>

        <!--BOTONES-->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-8">
                {% if usuario == 'COORDINADOR_EXPERTO' %}
                <a class="btn btn-sm btn-success" href="{% url 'mactor:matriz_mao' estudio.id 3%}" title="Matriz 3MAO"><i class="fa fa-arrow-left"></i> Atrás</a>
                {% else %}
                <a class="btn btn-sm btn-success" href="{% url 'mactor:matriz_mao' estudio.id 2%}" title="Consenso Matriz 2MAO"><i class="fa fa-arrow-left"></i> Matriz 2MAO</a>
                {% endif %}
                <a class="btn btn-primary" data-toggle="modal" href="#myModal" title="Ayuda"><i class="fa fa-book"></i> Ayuda</a>
                <a id="caa_daa" class="btn btn-primary" href="{%url 'mactor:consenso_caa_daa' estudio.id 3 1%}" title="Consenso matrices de convergencia y divergencia"><i class="fa fa-table"></i> CAA-DAA</a>
                <a class="btn btn-sm btn-success" href="{%url 'mactor:informe_final' estudio.id%}" title="Informe final">Informe <i class="fa fa-arrow-right"></i></a>
            </div>
        </div>

        <!--INICIO MODAL CONSULTAR ACTOR Y OBJETIVO----------------->

                    {% include 'actor/modal_detalle_actor.html' %}

                    {% include 'objetivo/modal_detalle_objetivo.html' %}

        <!--INICIO MODAL AYUDA------------------------------------->

         <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
             <div class="modal-dialog">
                 <div class="modal-content">
                     <div class="modal-header">
                         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                         <h4 class="modal-title">Ayuda - Matriz Valorada y Ponderada de Posiciones</h4>
                     </div>
                     <div class="modal-body" style="text-align: justify">
                         <p>
                             Al no depender las posibles alianzas y conflictos entre los actores solo de su
                             afinidad u oposición al desarrollo de los objetivos, sino también de la
                             capacidad de cada uno de estos para influir sobre el resto, se lleva a cabo el
                             cálculo de la matriz 3MAO, la cual se obtiene al multiplicar cada fila de la
                             matriz 2MAO por el Coeficiente Ri del actor correspondiente.<br><br>

                             Es decir mediante la matriz 3MAO, es posible analizar el nivel de convergencia y
                             divergencia de los actores, considerando además de la aptitud actual hacia los
                             objetivos el nivel de influencia entre los actores estudiados, evidenciándose
                             con ello con mayor claridad las alianzas y conflictos.
                         </p>
                     </div>
                     <div class="modal-footer">
                         <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                     </div>
                 </div>
             </div>
         </div>

    {% else %}
        <img src="{% static 'img/acceso_denegado.png' %}">
        <h2>Upps...no cuenta con los permisos necesarios para acceder a esta página.</h2>
    {% endif %}

{% block extrajs %}
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/js_mactor/js_mactor_modals/consultar/consultar_actor_objetivo_matriz.js'%}"></script>
{% endblock %}

{% endblock %}